### ISSUE TITLE
Role may fail in dry-run mode

### ISSUE THREAD

**Issue by manics** [openmicroscopy/ansible-role-omero-server#21]
Reported by @pwalczysko:
`TASK [openmicroscopy.omero-server : omero server | get latest version] **********************************************************************************************************************************************`
`fatal: [ ]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'url'\n\nThe error appears to have been in 'ansible-examples-omero/public-user/roles/openmicroscopy.omero-server/tasks/omero-install.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# operations instead\n- name: omero server | get latest version\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'url'"}`
This is because https://github.com/openmicroscopy/ansible-role-omero-server/blob/2.0.1/tasks/omero-install.yml#L32 is not run in check-mode, leading to the undefined variable later.

**Comment by kennethgillen** [comment]
Also encountered this during prod-server https://github.com/openmicroscopy/prod-playbooks/pull/13

**Comment by kennethgillen** [comment]
Also encountered during `--check` mode for ome-demoserver upgrade.

```

TASK [openmicroscopy.omero-server : omero server | get latest version] **********************************
fatal: [ome-demoserver.openmicroscopy.org]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'url'\n\nThe error appears to have been in '/Users/kenny/forks/infrastructure/ansible/vendor/openmicroscopy.omero-server/tasks/omero-install.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# operations instead\n- name: omero server | get latest version\n  ^ here\n"}
```

**Comment by kennethgillen** [comment]
Thanks to @manics for pointing out the fix.

**Comment by kennethgillen** [comment]
@sbesson  - ran successfully without `--check`

``
TASK [openmicroscopy.omero-server : omero server | get latest version] ********************************************************************************************************************************************
ok: [ome-demoserver.openmicroscopy.org]

```
