### ISSUE TITLE
running role on its own wiped top_links

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [openmicroscopy/ansible-role-omero-server#5]
Running role https://github.com/IDR/deployment/pull/9/files#diff-859e93e6ca33aa77acc85c0429403580R55 with default deployment vars in a upgrade context wiped top_links `omero.web.ui.top_links=[]`. Would be really nice if existing config is not affected in an upgrade mode

**Comment by manics** [comment]
It was run with a config file that explicitly sets it to `[]`: https://github.com/IDR/deployment/blob/3f41abc22bd9e8e9e6a0ac9da7e306533db9faef/ansible/files/IDR-OMERO-52-omero.j2#L58

**Comment by aleksandra-tarkowska** [comment]
I disagree, it was run with default group_vars, so I would expect to not change any state. Ideally would be to provide clear explanation what extra should be included on top of the server role to not change the state

**Comment by manics** [comment]
Those vars/options are set in a playbook in another repo, it's unrelated to this role.

**Comment by manics** [comment]
I think the best solution to this is https://github.com/openmicroscopy/design/issues/70

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : you ok with the status of this in openmicroscopy/design#70 ?

**Comment by joshmoore** [comment]
@manics: I'm assuming this is good to close then. Can re-open if you think this has any remaining TODOs.
